document.getElementById('myButton').addEventListener('click', function() {
    alert('Hello from JavaScript!');
});

const values = [
    "“Appear weak when you are strong, and strong when you are weak.”",
    "“The supreme art of war is to subdue the enemy without fighting.”",
    "“If you know the enemy and know yourself, you need not fear the result of a hundred battles. If you know yourself but not the enemy, for every victory gained you will also suffer a defeat. If you know neither the enemy nor yourself, you will succumb in every battle.”",
    "“Let your plans be dark and impenetrable as night, and when you move, fall like a thunderbolt.”",
    "“In the midst of chaos, there is also opportunity”",
    "“Supreme excellence consists of breaking the enemy's resistance without fighting.”",
    "“All warfare is based on deception. Hence, when we are able to attack, we must seem unable; when using our forces, we must appear inactive; when we are near, we must make the enemy believe we are far away; when far away, we must make him believe we are near.”",
    "“Victorious warriors win first and then go to war, while defeated warriors go to war first and then seek to win”",
    "“The greatest victory is that which requires no battle.”",
    "“If your enemy is secure at all points, be prepared for him. If he is in superior strength, evade him. If your opponent is temperamental, seek to irritate him. Pretend to be weak, that he may grow arrogant. If he is taking his ease, give him no rest. If his forces are united, separate them. If sovereign and subject are in accord, put division between them. Attack him where he is unprepared, appear where you are not expected .”",
    "“To know your Enemy, you must become your Enemy.”",
    "“There is no instance of a nation benefitting from prolonged warfare.”",
    "“Engage people with what they expect; it is what they are able to discern and confirms their projections. It settles them into predictable patterns of response, occupying their minds while you wait for the extraordinary moment — that which they cannot anticipate.”",
    "“Treat your men as you would your own beloved sons. And they will follow you into the deepest valley.”",
    "“Even the finest sword plunged into salt water will eventually rust.”",
    "“When you surround an army, leave an outlet free. Do not press a desperate foe too hard.”",
    "“Move swift as the Wind and closely-formed as the Wood. Attack like the Fire and be still as the Mountain.”",
    "“Opportunities multiply as they are seized.”",
    "“who wishes to fight must first count the cost”",
    "“There are not more than five musical notes, yet the combinations of these five give rise to more melodies than can ever be heard.",
    "“When the enemy is relaxed, make them toil. When full, starve them. When settled, make them move.”",
    "“The art of war is of vital importance to the State. It is a matter of life and death, a road either to safety or to ruin. Hence it is a subject of inquiry which can on no account be neglected.”",
    "“If you wait by the river long enough, the bodies of your enemies will float by.”",
    "“know yourself and you will win all battles”",
    "“To win one hundred victories in one hundred battles is not the acme of skill. To subdue the enemy without fighting is the acme of skill.”",
    "“So in war, the way is to avoid what is strong, and strike at what is weak.”",
    "“Be extremely subtle even to the point of formlessness. Be extremely mysterious even to the point of soundlessness. Thereby you can be the director of the opponent's fate.”",
    "“The wise warrior avoids the battle.”",
    "“Build your opponent a golden bridge to retreat across.”",
    "Some plants communicate with each other through a network of fungi in the soil, often called the \"wood wide web.\"",
    "The world's largest flower, the Rafflesia arnoldii, can grow up to 3 feet across. It also smells like rotting meat to attract flies for pollination.",
    "Dandelions are completely edible, from the roots to the flowers.",
    "The smell of freshly cut grass is actually a chemical distress signal released by the plant.",
    "The titan arum is also known as the corpse flower because of the foul odor it produces to attract pollinators. It has the world's largest unbranched inflorescence (a cluster of flowers).",
    "Bamboo is one of the fastest-growing plants, with some species able to grow up to 35 inches in a single day.",
    "The baobab tree can store thousands of gallons of water in its trunk.",
    "Carrots were originally purple before they were selectively bred for their orange color.",
    "The oldest living non-clonal tree is a bristlecone pine named Methuselah, which is over 4,800 years old.",
    "Banana plants are technically herbs, not trees, because their stems lack woody tissue.",
    "The longest-living plant is a seagrass colony in Spain estimated to be up to 100,000 years old.",
    "Small pockets of air inside cranberries cause them to float and bounce.",
    "The vanilla bean comes from an orchid.",
    "Some seeds, like those of the lotus plant, can remain viable for centuries. The oldest germinating seed on record was a Judean date palm seed that sprouted after nearly 2,000 years.",
    "There are over 80,000 species of edible plants on Earth, but humans get 90% of their food from just 30 plants.",
    "A notch in a tree will remain the same distance from the ground as the tree grows.",
    "Peanuts are not nuts; they are legumes.",
    "The longest-living organism on Earth is a clonal colony of quaking aspens in Utah, known as Pando, which is estimated to be over 80,000 years old.",
    "Coffee and tea plants produce caffeine as a natural pesticide to ward off pests.",
    "Apples and roses belong to the same family.",
    "Some plants can produce their own antifreeze, allowing them to survive in freezing temperatures.",
    "There are some plants, like the sensitive plant, that move their leaves when touched in a rapid response.",
    "The sandbox tree is known for its exploding fruit that spreads seeds.",
    "Sunflowers can be used to clean up toxic soil by absorbing harmful pollutants.",
    "85% of all plant life on Earth is found under the ocean.",
    "Your brain is a dried-up sponge.",
    "You're about as sharp as a marble.",
    "Do you have a license to be that dense?",
    "I've seen smarter things written on a bathroom stall.",
    "You couldn't think your way out of a paper bag.",
    "You're not just dumb, you're a special kind of stupid.",
    "It's amazing you remember to breathe.",
    "You're an intellectual black hole.",
    "I'm convinced your brain is on a permanent vacation.",
    "You look like a before picture.",
    "You have a face for radio.",
    "You're the kind of person who makes me believe in evolution, just in reverse.",
    "I’m not saying you’re ugly, but you’d make a scarecrow run away.",
    "You have a personality that would make a rock look interesting.",
    "You're living proof that not all heroes wear capes, and not all people are interesting.",
    "You're the human equivalent of a participation trophy.",
    "Your personality is as bland as unseasoned chicken.",
    "I've met more interesting lint.",
    "You’re about as useful as a screen door on a submarine.",
    "You bring nothing to the table but a lack of effort.",
    "You’re the reason why instruction manuals exist.",
    "You couldn't pour water out of a boot with instructions on the heel.",
    "You're a walking, talking mistake.",
    "If incompetence was an art form, you'd be a masterpiece.",
    "You're so good at failing, it's almost impressive.",
    "You're the weakest link in this chain.",
    "You're a solution looking for a problem.",
    "You're the human version of a headache.",
    "I'd agree with you, but then we'd both be wrong.",
    "I’m trying to imagine you with a personality, but my brain isn’t that creative.",
    "I don't know what your problem is, but I bet it's hard to pronounce.",
    "Your existence is a testament to the power of pure luck.",
    "You're the reason they invented the mute button.",
    "If you were any dumber, we'd have to water you twice a week.",
    "I've had more fun watching paint dry.",
    "You're about as welcome as a fart in a spacesuit.",
    "You're a disappointment, plain and simple.",
    "I'd tell you to get a life, but you'd just screw that up, too.",
    "Your life is a cautionary tale.",
    "You're a living embodiment of the phrase \"missed potential.\"",
    "The only thing you've ever accomplished is being a failure.",
    "Your greatest achievement is making everyone around you look good.",
    "I feel sorry for anyone who has to deal with you on a daily basis.",
    "Your life is a train wreck in slow motion.",
    "You're not going anywhere in life, and that's okay, because you'll get lost on the way."
    ];

function generateRandomValue() {
            // Get a random index from 0 to the length of the values array
            const randomIndex = Math.floor(Math.random() * values.length);
            
            // Get the value at that random index
            const randomValue = values[randomIndex];

            // Update the text content of the display area
            displayValue.textContent = randomValue;
        }
